<h1 align = center>Numpy Library - Sorting Arrays</h1>

## Basic Sorting 


### Ascending Sorting
Create a 1D NumPy array with random integers between 1 and 100. Sort the array in ascending order.

In [1]:
import numpy as np
array = np.array([34, 12, 5, 7, 56, 89, 22, 45])
print(f"original array : {array}")

sorted_array = np.sort(array)
print(f"sorted array : {sorted_array}")

original array : [34 12  5  7 56 89 22 45]
sorted array : [ 5  7 12 22 34 45 56 89]


### Sorting in Descending Order
- The numpy library does not support descending sorting. 
- However we can sort an array in ascending order and then revers the order of array element and can achieve the same result as descending order. 
  - We can reverse the elements of an array using the advance indexing technique that is used for make array slices with a step size. That is `array[start_index : stop_index : step_size]`.
  - Here, if we write simple colons in place of both start index and stop index, it will mean that we want ot select all the elements. 
  - The third argument will mention a step size for element selection. 
  - Here if we write -1 in place of the step size, it will indicate that we want to fetch elements starting from the last index.

In [2]:
# here is how elements are selected starting from the last index
a = np.arange(1,16)
print(a)
print(a[ 3 : 8 : 1])
print(a[ 0 : 16 : 2])

# starting from last index
print(a[::-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[4 5 6 7 8]
[ 1  3  5  7  9 11 13 15]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


- Now, lets create a 1D NumPy array of integers and Sort it in descending order.

In [3]:
array = np.array([67, 89, 54, 72, 95, 62])
print(f"original array : {array}")

sorted_array = np.sort(array)
sorted_array = sorted_array[: : -1]
print(f"sorted array : {sorted_array}")

original array : [67 89 54 72 95 62]
sorted array : [95 89 72 67 62 54]


## Sorting Along a Specific Axis in Multi-Dimensional Arrays

### Sorting with `np.sort()`
- Given a 2D array, let us sort the arrays according to rows.
  - In this case, all the rows will be arranged in order. 
  - When we sort a 2D array according to its rows, we often think that the elements of each row will be sorted but this is not the case, instead, when we sort a 2D array according to rows, it is not the row elements that are sorted, rather rows are arranged according to the first element of each row in ascending order. Then it proceeds with the next element and 2nd element of all the rows are arranged in ascending order and so on. 
  - Of course, in this process, the contents of each row are changed. The rows we get once the sorting according to the rows is complete are completely different than the original rows.
  - Sorting an array according to the rows is achieved via `axis` argument, where a value `0` is considered as row wise sorting. 

In [6]:
array = np.array([[25, 12, 7],
                  [18, 5, 23],
                  [45, 35, 10]])

print(f"the original array : \n\n{  array   }")

sorted_array = np.sort(array, axis = 0)
print(f"the sorted array : \n\n{     sorted_array    }")

the original array : 

[[25 12  7]
 [18  5 23]
 [45 35 10]]
the sorted array : 

[[18  5  7]
 [25 12 10]
 [45 35 23]]


__Note Here__
- That the elements of each row are not same after sorting as compared to the original array. 

We can also sort our array according to its columns using `axis = 1`. 

In [7]:
array = np.array([[12, 5, 9],
                  [8, 15, 3],
                  [2, 25, 7]])
print(f"the original array : \n\n{  array   }")

sorted_array = np.sort(array, axis = 1)
print(f"the sorted array : \n\n{     sorted_array    }")

the original array : 

[[12  5  9]
 [ 8 15  3]
 [ 2 25  7]]
the sorted array : 

[[ 5  9 12]
 [ 3  8 15]
 [ 2  7 25]]


__We can see__ that by sorting the array on `axis = 1` or according to columns, results in such an array in which:
- The position of rows does not change.
- All the elements of each row are sorted in ascending order. 
- The elements of each row are the same as they were in the original array. 

### Sorting with `np.argsort()`
- It returns the indices that would sort an array. Instead of returning the sorted values, it gives you the indices that represent the order in which the elements of the array should be arranged to obtain a sorted version.
- __Syntax__:
  - `numpy.argsort(our_array, axis=-1, kind=None, order=None)`
  - our_array: The input array that you want to sort.
    - axis: The axis along which to sort the array. Default is -1, which means the last axis. If the array is 1D, there’s only one axis.
    - kind: The sorting algorithm to use. You can choose from:
      - 'quicksort' (default)
      - 'mergesort'
      - 'heapsort'
      - 'stable'
    - order: When sorting a structured array, you can specify which fields to compare. Otherwise, this is usually set to None.

In [10]:
# sorting 1D arrays

our_array = np.array([22,10,35,38,2,5,56,3,19])
print(f"The original array : {  our_array   }")

sorting_indices = np.argsort(our_array)
print(f"Indices to sort the elements : {    sorting_indices }")

sorted_array = our_array[sorting_indices]
print(f"Sorting array using the indices : {     sorted_array    }")

The original array : [22 10 35 38  2  5 56  3 19]
Indices to sort the elements : [4 7 5 1 8 0 2 3 6]
Sorting array using the indices : [ 2  3  5 10 19 22 35 38 56]


In [13]:
# sorting multi dimensional arrays
our_array = np.array([
    [3, 1, 2], 
    [9, 7, 8]
    ])

print(f"The original array : \n\n{  our_array   }")

sorting_indices = np.argsort(our_array, axis = 1)
print(f"Indices to sort the elements : \n\n{    sorting_indices }")


The original array : 

[[3 1 2]
 [9 7 8]]
Indices to sort the elements : 

[[1 2 0]
 [1 2 0]]


__Unfortunately__ in the case of a multi dimensional array, we cannot simply pass the indices returned by `np.argsort()` to our original array to access its elements in sorted order, rather, we need a special numpy method called `np.take_along_axis()` that requires the original array, sorting indices returned by the argsort method and the axis as its 3 arguments and returns the desired elements as an input.

In [15]:
sorted_array = np.take_along_axis(our_array, sorting_indices, axis = 1)
print(f"Sorting array using the indices : \n\n{     sorted_array    }")

Sorting array using the indices : 

[[1 2 3]
 [7 8 9]]
