<h1 align = center>Numpy Library - Indexing, Slicing and Filtering Arrays</h1>

## Indexing Array Elements

### Indexing 1D Arrays

In [1]:
import numpy as np

In [2]:
an_array = np.array([1,2,3,4,5])
second_element = an_array[1]
fifth_element = an_array[4]
first_element_from_last = an_array[-1]
third_element_from_last = an_array[-3]


print(f'second element : {second_element}')
print(f'fifth element : {fifth_element}')
print(f'first element from the last : {first_element_from_last}')
print(f'third element from the last : {third_element_from_last}')

second element : 2
fifth element : 5
first element from the last : 5
third element from the last : 3


### Indexing 2D-Arrays

In [3]:
# defining a 2D array
b_array = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

b_array.shape

(3, 5)

#### Accessing rows

In [4]:
print(f'first row : {   b_array[0]  }')
print(f'second row : {  b_array[1]  }')

first row : [1 2 3 4 5]
second row : [ 6  7  8  9 10]


#### Accessing Multiple Rows at a Time
- Multiple row are accessed using `:`. A colon indicates a range of rows (or columns for that matter).
- __Syntax__
  - `our_array[starting_index : ending_index]`
  - Here starting index is included while selecting rows/columns, but the ending index is not included. That means, if we write 10 in place of ending index, the row at index 10 will not be included, instead, rows till index 9 will be included. 

In [5]:
# this will select rows at index 0 and 1, where index 2 will not be included. 
print(f'first two rows : \n{b_array[0:2]}') 

first two rows : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


- A simple colon `:` without any starting or ending index will select all the rows

In [6]:
# selecting all the rows
print(f"all the rows selected with colon `:` \n{    b_array[ : ]}")

all the rows selected with colon `:` 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


#### Accessing Columns 
- The `:` in place of row index indicates that we want to select all the rows and while selecting a column, we do need all the rows as how can we get a complete column if any row is missing? That is why we need all the rows, hence we use `:` for the said purpose. 
- The column index is mention after the row index, where both row and column indexes are separated using a comma `,`. 
- __Syntax__:
  - array_name[row_indexes , column indexes]
  - Using columns `:` in place of both, rows and columns will fetch all the rows and all the columns.

In [7]:
print(f'second column : {    b_array[:,1]   }')
print(f'fourth column : {   b_array[:,3]    }')
print(f'last column : {     b_array[:,-1]   }')

second column : [ 2  7 12]
fourth column : [ 4  9 14]
last column : [ 5 10 15]


In [9]:
b_array[: , :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

#### Accessing a Particular Set of Elements from ND-Arrays

- 4 elements from top left

In [10]:
b_array[0:2, 0:2]

array([[1, 2],
       [6, 7]])

- Accessing 4th and 5th elements of the second and third row respectively. 

In [13]:
b_array[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

### Accessing Elements in a 3D array

In [17]:
c_array = np.array(
    [

        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ],
        [
            [13, 14, 15],
            [16, 17, 18]
        ]

    ]
)

print(c_array)
print(f"array shape : {c_array.shape}")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
array shape : (3, 2, 3)


#### Accessing a Complete Inner Array

In [20]:
c_array[0]

array([[1, 2, 3],
       [4, 5, 6]])

#### Accessing a Range of Complete Inner Arrays

In [19]:
c_array[1:3] # last two inner arrays

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

#### Accessing a Single Row from a Single Inner List

In [41]:
'''
1. first row of second inner array

c_array[1 , 0]
the 1 indicates which outer list to select, here we are selecting outer list at index 1
the 0 indicates inside selected list at index 1, which inner list we want to access
'''
c_array[1 , 0]



array([7, 8, 9])

In [42]:
# second row of third inner array
c_array[2 , 1]


array([16, 17, 18])

#### Accessing a Column
- Accessing a column is tricky in a 3D array.
- The first argument reflects which of the outer lists we want to select, the second argument reflects which rows of these lists we want to select and third index reflects which columns to select. 

In [44]:
# 2nd columns of all the lists
c_array[: , : , 1]

array([[ 2,  5],
       [ 8, 11],
       [14, 17]])

In [45]:
# 1st column of all the lists 
c_array[: , : , 0]

array([[ 1,  4],
       [ 7, 10],
       [13, 16]])

#### Accessing a Single Element
- Selecting 14 from the third inner list.

In [50]:
c_array[2 , 0 , 1]

14

## Filtering Arrays 
- There are two main methods to filter numpy arrays:
    1. Masking Method
    2. `np.where()` Method