<h1 align = center>Numpy Library - Managing Array Dimensionality</h1>

In [1]:
# importing numpy here
import numpy as np

## Checking The Dimensions of a Numpy Array
- The `shape()` property of an array tells us its dimensionality, unlike other common numpy functions, it is not called on `np` module, rather its called on the actual array object. Lets dive in:

In [2]:
an_array = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
print(an_array)

array_dimensions = an_array.shape
print(f'The dimensions of this array are : {array_dimensions}')
print(f'That means we have {array_dimensions[0]} rows and {array_dimensions[1]} columns in this 2D array/matrix.')

[[1 2 3]
 [4 5 6]]
The dimensions of this array are : (2, 3)
That means we have 2 rows and 3 columns in this 2D array/matrix.


## A Deeper Look on Dimensionality
- The 1D arrays are simple vectors. There is not concept of rows or columns in 1D arrays since no such information is provided during their creation. 
- For the reason provided above, although our 1D array is a vector, still we cannot say if its a row vector or a column vector. 
- For example, have a look at the following 1D array:

In [3]:
one_d_array = np.ones(5) # only values are mentioned, no row or column information provided. 
print(f'Our first 1D array is \n{one_d_array} \nand its dimensions are {one_d_array.shape}')

Our first 1D array is 
[1. 1. 1. 1. 1.] 
and its dimensions are (5,)


- We can see here, that the shape is `(5,)` which means, our array consists of 5 values. The shape property is not giving us any information about the rows or columns. 
- Now have a look at another 1D array:

In [4]:
another_array = np.ones((1,5)) 
print(f'Our second array is \n{another_array} \nand its dimensions are {another_array.shape}')

Our second array is 
[[1. 1. 1. 1. 1.]] 
and its dimensions are (1, 5)


- We can see, that both of these arrays looks the same. Just like a list of values as in a simple array. 
- But if we examine closely, where the shape of the first array was `(5,)`, the shape of the second array is a little different, that is `(1,5)`. 
- Although it looks the same, the first array is just a collection of 5 values, a vector, while the second array is basically a matrix of one row and 5 columns. In other words its a row vector.
- If we interchange the rows and column, we will see that our array will be shown vertically, indicating a single column and 5 rows. Lets try it:

In [5]:
yet_another_array = np.ones((5,1)) 
print(f'Our third array is \n{yet_another_array} \nand its dimensions are {yet_another_array.shape}')

Our third array is 
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]] 
and its dimensions are (5, 1)


## Reshaping a Numpy Array / Changing its Dimensions 
- Numpy facilitates us in changing the dimensionality of an array. 
- There are two main array methods to change the dimensionality, `flatten()` and `reshape`.

### Flatten an Array
- By flattening an array we mean that if we have a matrix of n x n columns, we can reshape this matrix in such a way that all its rows will be placed in a single row and we will get a new 1D array instead of this matrix. 
- In this array, each row of the matrix is placed after its previous row and hence we get an array consisting of single row. 
- This newly created array is called a `flattened array`. 

In [6]:
# creating a matrix of random numbers having dimensions 3x3
a_matrix = np.ones((3,4)) 
print(a_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


- Now lets flatten this matrix into a 1D array

In [7]:
flattened_matrix = a_matrix.flatten() # notice, flatten() is called on our numpy array, its a method of array object, not a function of numpy. 
print(flattened_matrix)
print(f'shape : {flattened_matrix.shape}')

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
shape : (12,)


### Changing Number of Row and Columns via Array Reshaping
- The `flatten()` method does not care about the information of rows and columns in the original matrix. Everything is placed inside a single row. 
- The `reshape()` method on the other hand allows us to mold our matrix into our desired dimension by taking required number of rows and columns as its argument. Lets dive in:

In [8]:
print(f'our original matrix was\n\n{a_matrix}\n')
print(f'shape : {a_matrix.shape}')

our original matrix was

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

shape : (3, 4)


- We can change its dimensions to `2 x 6` using the `reshape()` method.

In [9]:
changed_dimensionality = a_matrix.reshape(2,6)
print(changed_dimensionality)
print(f'shape : {changed_dimensionality.shape}')

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
shape : (2, 6)


- Lets change it to `6 x 2`.
  

In [10]:
changed_dimensionality = a_matrix.reshape(6,2)
print(changed_dimensionality)
print(f'shape : {changed_dimensionality.shape}')

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
shape : (6, 2)


- Now to `4 x 3`

In [11]:
changed_dimensionality = a_matrix.reshape(4,3)
print(changed_dimensionality)
print(f'shape : {changed_dimensionality.shape}')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
shape : (4, 3)


- Now to `12 x 1`. 

In [12]:
changed_dimensionality = a_matrix.reshape(12,1)
print(changed_dimensionality)
print(f'shape : {changed_dimensionality.shape}')

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
shape : (12, 1)


- Changing this column vector back to the original `3 x 4` matrix. 

In [13]:
print(f'original shape : {changed_dimensionality.shape}')

changed_dimensionality = changed_dimensionality.reshape(3,4)

print(f'changed back to original matrix')

print(changed_dimensionality)
print(f'shape : {changed_dimensionality.shape}')

original shape : (12, 1)
changed back to original matrix
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
shape : (3, 4)


### Automatically Calculating One of the Dimension
- Using -1 as `one of the dimensions` allows NumPy to automatically calculate the correct size for `second dimension` based on the one dimension that is supplied and total number of elements.
- Have a look at the following example for better understanding:

In [14]:
# Create a 1D array with 12 elements
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape it to a 2x6 array using -1 to infer the second dimension
reshaped_array = array.reshape(2, -1)
print('using -1 inplace of column dimensions')
print(reshaped_array)

# Reshape it to a 6x2 array using -1 to infer the second dimension
reshaped_array = array.reshape(-1, 6)
print('using -1 inplace of row dimensions')
print(reshaped_array)

using -1 inplace of column dimensions
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
using -1 inplace of row dimensions
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


- __A Note of Reshaping__ :
  - It is worth mentioning here that a shape can only be converted into a compatible shape. 
  - By compatible shape we mean that the original array must have enough elements to populate the newly requested shape. On the other hand, the newly requested shape must accommodate all the elements of the original array, we cannot leave any element out. 
  - For example an array of `4 x 3` cannot be converted into a `5 x 5` array. The reason is simple the `4 x 3` array have 12 elements while the newly requested shape `5 x 5` requires 25 elements which are not available. 