<h1 align = center>Numpy Library - Array Creation</h1>

**Table of contents**<a id='toc0_'></a>    
- [Creating Numpy Arrays](#toc1_1_)    
    - [Creating Multi-Dimensional Numpy Arrays](#toc1_1_1_)    
    - [Checking the Shape/Dimensions of a Numpy Array](#toc1_1_2_)    
  - [Some Commonly Used Special Numpy Arrays/Matrices](#toc1_2_)    
    - [A Matrix of Zeros](#toc1_2_1_)    
    - [A Matrix of Ones `1s`](#toc1_2_2_)    
    - [A Matrix of Random Numbers](#toc1_2_3_)    
    - [A Matrix Filled with a Single Values of Our Choice](#toc1_2_4_)    
    - [An Array of Numbers With Custom Lower and Upper Bound](#toc1_2_5_)    
    - [An Identity Matrix](#toc1_2_6_)    
      - [An Identity Matrix with Custom Diagonal](#toc1_2_6_1_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

## <a id='toc1_1_'></a>[Creating Numpy Arrays](#toc0_)

In [1]:
# to use numpy, we have to import it first. (of course it must have been installed in the first place) 
import numpy as np

- Numpy array is created using `array()` method of numpy library. 
- This method requires a python `list` as an argument. We can not only pass required values in the form of list to create a new array can also pass an existed list as an argument and the array() method will convert it into a numpy array. 
- __Syntax__
  - `np.array([a_list_of_elements])`

In [2]:
# creating one dimensional numpy arrays
a_numpy_array = np.array([1,2,3,4,5])

print(a_numpy_array)
print(type(a_numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### <a id='toc1_1_1_'></a>[Creating Multi-Dimensional Numpy Arrays](#toc0_)
- The simple array, created from a simple list are called 1 dimensional arrays. But numpy allows us to create arrays from lists of lists. In this case, these array are called multidimensional arrays. 
- If we are to create a numpy array form a list of lists, it will be called a 2 dimensional array. In the case of list of lists of lists, it will be called a 3 dimensional array and so on. 
- The syntax is simple, we just need to pass our list of lists to the array() method 

In [3]:
'''
Creating a 2D Array
'''
list_of_lists = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]

two_d_array = np.array(list_of_lists)

print(two_d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
'''
Creating a 3D array
'''
list_of_lists_of_lists = [
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
]

three_d_array = np.array(list_of_lists_of_lists)

print(three_d_array)
print(type(three_d_array))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
<class 'numpy.ndarray'>


### <a id='toc1_1_2_'></a>[Checking the Shape/Dimensions of a Numpy Array](#toc0_)
- We can use the `shape` property of a numpy array object to check its dimensions.

In [5]:
print('The shape of our previous created arrays are as follows: ')

shape_one = a_numpy_array.shape
shape_two = two_d_array.shape
shape_three = three_d_array.shape

print(f'The shape of a simple numpy array is : {shape_one}')
print(f'The shape of a 2D numpy array is : {shape_two}')
print(f'The shape of a 3D numpy array is : {shape_three}')

The shape of our previous created arrays are as follows: 
The shape of a simple numpy array is : (5,)
The shape of a 2D numpy array is : (3, 3)
The shape of a 3D numpy array is : (3, 2, 3)


- We can see here, that 1D array has just one row and zero columns, while 2D array is like a matrix having 3 rows and 3 columns. More than 2 dimensional array is called a `tensor` so our 3D array which is actually a tensor, has dimension (3,2,3) which states that there are 2 rows and 2 columns for each matrix and there are total 3 matrix.

## <a id='toc1_2_'></a>[Some Commonly Used Special Numpy Arrays/Matrices](#toc0_)

### <a id='toc1_2_1_'></a>[A Matrix of Zeros](#toc0_)
- Numpy provides a special method `np.zeros()` to create an array of our desired dimensions filled with zeros. This type of array is useful when we are working on a kind of data in which we need an array having specific dimensions and we will fill it with values as we progress through our program, a neural network is a widely known example. 
- __Syntax__:
  - `np.zeros((a_tuple_stating_dimensions))`
  - Note here, that we are not using `np.array()`, rather a different method `np.zeros()` is being used. 
  - Also note here, that unlike `np.array()` method, we are not passing a list as an argument, rather we are passing a tuple of dimensions. 

In [6]:
tuple_of_dimensions = (3,4) # we want to create an array having 3 rows and 4 columns 

array_of_zeros = np.zeros(tuple_of_dimensions)
print(f'Array with tuple already defined :\n{array_of_zeros}')

array_of_zeros = np.zeros((8,4))
print(f'Array with dimensions directly supplied :\n{array_of_zeros}')



Array with tuple already defined :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array with dimensions directly supplied :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### <a id='toc1_2_2_'></a>[A Matrix of Ones `1s`](#toc0_)
- Just like an array of zeros, numpy also allows us to create arrays filled with `1s`. 
- __Syntax__:
  - `np.ones(tuple_of_array_dimensions)`

In [7]:
array_of_ones = np.ones((6,3))
print(array_of_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### <a id='toc1_2_3_'></a>[A Matrix of Random Numbers](#toc0_)
- Just like array of zeros, we can also create an array filled with random numbers and having our desired dimensions.
- The created array will have random numbers between 0 and 1
- __Syntax__:
  - `np.random.random((a_tuple_of_dimensions))`

In [8]:
random_numbers_array = np.random.random((6,3))
print(random_numbers_array)

[[0.08254388 0.37054059 0.98414135]
 [0.34307166 0.96699003 0.25823118]
 [0.58237019 0.69407554 0.58347576]
 [0.91503993 0.70674127 0.94743637]
 [0.63196821 0.65150314 0.99358887]
 [0.33202798 0.39788045 0.41296186]]


### <a id='toc1_2_4_'></a>[A Matrix Filled with a Single Values of Our Choice](#toc0_)
- With numpy, we can create a matrix of our desired dimensions and filled with a single value of our choice. This is achieved using ``np.full()` method. 
- __Syntax__:
  - `np.full(dimensions_tuple, value_to_fill)`
  - All the parameters supported by np.full:
    - `shape`: This is a tuple that defines the shape of the array. For example, (3, 4) would create an array with 3 rows and 4 columns.
    - `fill_value`: The value with which to fill the array. This can be any scalar value like an integer, float, etc.
    - `dtype` (optional): The desired data type of the array. If not specified, NumPy will infer the data type from the fill_value.
    - `order` (optional): The memory layout of the array. 'C' means C-style row-major order (rows are stored sequentially), and 'F' means Fortran-style column-major order (columns are stored sequentially).
    - `like` (optional): Reference object to allow the creation of arrays that are similar to an existing array.

In [26]:
custom_value_array = np.full(10, 99) # 1D array of 10 elements, filled with integer 99. 
print(f'1D array with np.full \n{custom_value_array}')


custom_value_matrix = np.full((5,5), 99) # 2D matrix of 5x5 dimensions, filled with integer 99. 
print(f'2D matrix with np.full \n{custom_value_matrix}')

1D array with np.full 
[99 99 99 99 99 99 99 99 99 99]
2D matrix with np.full 
[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


### <a id='toc1_2_5_'></a>[An Array of Numbers With Custom Lower and Upper Bound](#toc0_)
- Numpy facilitates us in creating arrays filled with numbers with a user defined lower and upper range of these numbers. 
- This kind of array is a one dimensional array. 
- The numbers are not random, but in a continues sequence.
- __Syntax__:
  - `np.arange(lower_bound, upper_bound, step_size(optional))`
  - Note here that the argument is neither a list nor a tuple but a simple comma separated set of arguments mentioning lower and upper bounds. 
  - The lower bound number is included in the result, while the upper bound number is not included. 
- __With Step Size__:
  - We can also pass a step size as a third argument after the lower and upper bounds. The generated numbers will have a gap equal to the mentioned step size.

In [9]:
lower_bound = 1
upper_bound = 21
step_size = 2

# without step size
random_array_with_custom_bounds = np.arange(lower_bound, upper_bound)
print(random_array_with_custom_bounds)

# with step size
with_step_size = np.arange(lower_bound, upper_bound, step_size)
print(with_step_size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  3  5  7  9 11 13 15 17 19]


### <a id='toc1_2_6_'></a>[An Identity Matrix](#toc0_)
- An identity matrix is a special kind of square matrix (a matrix with the same number of rows and columns) in which all the elements of the principal diagonal (from the top left to the bottom right) are equal to 1, and all other elements are equal to 0.
- __Syntax__:
  - `np.identity(rows, optional_data_type_of_numbers)`
  - It requires only number of rows and will create a square matrix accordingly, we cannot provide number of columns here. 
  - Data type as the second argument refers to the data type of numbers that will be filled in the matrix which are 0 and 1. 


In [17]:
# identity matrix with numpy
identity_matrix = np.identity(4)
print(identity_matrix)

print('____\n')
# with data type mentioned
identity_matrix = np.identity(5)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
____

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### <a id='toc1_2_6_1_'></a>[An Identity Matrix with Custom Diagonal](#toc0_)
- The `np.identity()` method creates a pure identity matrix, and does not allow us to change its diagonal. 
- There is another useful method `np.eye` which allows us to generate custom identity matrices which our custom diagonal (means on which diagonal we want ot have 1 values). 
- It also facilitates us to mention custom matrix dimensions instead of a square matrix. 
- We can say that is a specialized form of identity matrix and not the original identity matrix. 
- __Syntax__:
  - `np.eye(rows, columns, k (desired diagonal))`
  - A positive k values moves the diagonal to the right, while a negative k values moves the diagonal to the left. 

In [18]:
custom_identity_matrix = np.eye(5,10)
print(custom_identity_matrix)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


- **_Here_** we can see that the diagonal is starting from the first column of the first row, however we can move it to our desired position using the `k` value. 

In [19]:
custom_identity_matrix = np.eye(5,10,3)
print(custom_identity_matrix)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


- **_Note Here_** that the 1s are not staring from the 4th column of the first row. 