<h1 align = center>Numpy Library - Indexing, Slicing and Filtering Arrays</h1>

## Indexing Array Elements

### Indexing 1D Arrays

In [2]:
import numpy as np

In [3]:
an_array = np.array([1,2,3,4,5])
second_element = an_array[1]
fifth_element = an_array[4]
first_element_from_last = an_array[-1]
third_element_from_last = an_array[-3]


print(f'second element : {second_element}')
print(f'fifth element : {fifth_element}')
print(f'first element from the last : {first_element_from_last}')
print(f'third element from the last : {third_element_from_last}')

second element : 2
fifth element : 5
first element from the last : 5
third element from the last : 3


### Indexing ND-Arrays

In [4]:
# defining a 2D array
b_array = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

b_array.shape

(3, 5)

#### Accessing rows

In [7]:
print(f'first row : {   b_array[0]  }')
print(f'second row : {  b_array[1]  }')

first row : [1 2 3 4 5]
second row : [ 6  7  8  9 10]


#### Accessing Multiple Rows at a Time
- Multiple row are accessed using `:`. A colon indicates a range of rows (or columns for that matter).
- __Syntax__
  - `our_array[starting_index : ending_index]`
  - Here starting index is included while selecting rows/columns, but the ending index is not included. That means, if we write 10 in place of ending index, the row at index 10 will not be included, instead, rows till index 9 will be included. 

In [9]:
# this will select rows at index 0 and 1, where index 2 will not be included. 
print(f'first two rows : \n{b_array[0:2]}') 

first two rows : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


- A simple colon `:` without any starting or ending index will select all the rows

In [10]:
# selecting all the rows
print(f"all the rows selected with colon `:` \n{    b_array[ : ]}")

all the rows selected with colon `:` 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


#### Accessing Columns 

In [6]:
print(f'second column : {    b_array[:,1]   }')
print(f'fourth column : {   b_array[:,3]    }')
print(f'last column : {     b_array[:,-1]   }')

second column : [ 3  8 13]
