<h1 align = center>Numpy Library - Array Manipulations</h1>

# Basics of Concatenation & Stacking

In [1]:
import numpy as np

## Overview of Concatenation vs. Stacking
- In NumPy, concatenation and stacking are techniques to join arrays, but they differ in subtle ways.
- **Concatenation**: 
  - This is used to join arrays along an **existing axis**. For instance, if you're working with a 2D array, you can concatenate arrays along the row axis (axis=0) or column axis (axis=1).
- **Stacking**: 
  - This is more flexible, as it can add a new axis (dimension) when combining arrays. Instead of just joining along an existing axis, you create higher-dimensional arrays.

## Differences Between Axis, Dimensions, and Shape Manipulation
- Understanding axes and dimensions is crucial when working with concatenation and stacking. Let's break this down:
- **Axes**: 
  - In a NumPy array, an axis is like a direction or dimension along which the array elements are organized. Think of axes as coordinates in space:
    - Axis 0 refers to the rows in 2D arrays.
    - Axis 1 refers to the columns in 2D arrays.
    - Higher axes (e.g., 2, 3) refer to additional dimensions in multi-dimensional arrays.
- **Dimensions**: 
  - The number of dimensions (or rank) of an array is determined by its shape. A 1D array has one dimension (like a vector), a 2D array has two dimensions (like a matrix), and so on.

In [2]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.shape)  

(3, 2)


This tells us that arr has 3 rows and 2 columns.

- **Shape manipulation**: 
    - When concatenating or stacking, the **shapes** of arrays must often be **compatible**, **especially when using concatenation**. If they aren't, you might need to reshape or transpose the arrays.
- Example of shape mismatch:

In [3]:
arr1 = np.array([[1, 2], [3, 4]])  # shape (2, 2)
arr2 = np.array([[5, 6, 7]])       # shape (1, 3)

# This will raise an error:
# result = np.concatenate((arr1, arr2), axis=0)


To fix this, you may need to reshape the arrays to have compatible dimensions.

## Choosing Between Concatenation and Stacking
- When to use concatenation:
  - When you want to merge arrays along an existing dimension (e.g., adding more rows or columns to a 2D array).
  - The arrays you are merging already have compatible shapes along the dimensions you're interested in.
- When to use stacking:
  - When you need **to create a new dimension** in the resulting array.
  - The **original arrays do not have the exact number of dimensions** or axes you want to merge, and you prefer **to introduce a new axis** to combine them.
  - Use stack() when you need more control over where the new axis is created.

# Array Concatenation


### Concatenating Single Dimensional Arrays
- Syntax: `np.concatenate(tuple_of_arrays_to_concatenate)`
- This function receives all the arrays to be concatenated as a first argument. These arrays are supplied in the form of a tuple. 
- The shape must be compatible for concatenation purpose. If we want to place the second array bellow the first array, the number of columns must be equal and if we want to place the second array at the right side of the first array to increase its columns by including the columns of the second array, the number of rows must be equal. It the case of single dimensional arrays, the shape is always the same for both i.e., compatible. 

In [4]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

shape1 = x.shape
shape2 = y.shape

print(f"The shape of first array is : {shape1}\nThe Shape of the second array is : {shape2}")

The shape of first array is : (5,)
The Shape of the second array is : (5,)


Discussion:
- The shapes reveal that both of these arrays have only rows and no value for columns. That simply means that these are single dimensional arrays same as a collection of values in a python list.
- As both of these arrays have same shape, these array can be concatenated. 

In [5]:
tuple_of_arrays_to_concatenate = (x, y)
z = np.concatenate(tuple_of_arrays_to_concatenate)
print(z.shape)
print(z)

(10,)
[ 1  2  3  4  5  6  7  8  9 10]


- **Its Simple:** 
  Concatenating single dimensional arrays is straight forward, things get tricky, once we try to concatenate multi dimensional arrays, such as 2D arrays. 
  Note Here: that the shape of arrays is the same, after the concatenation, it is not the case in array stacking. We shall see it later in stacking.

### Concatenating 2D/Multi-Dimensional Arrays


In [6]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
y = np.array([
    [-1,-2,-3,-4],
    [-5,-6,-7,-8]
])

shape1 = x.shape
shape2 = y.shape

print(f"The shape of first array is : {shape1}\nThe Shape of the second array is : {shape2}")

The shape of first array is : (2, 4)
The Shape of the second array is : (2, 4)


Discussion:
- The shapes explain that both of these arrays have 2 rows and 4 columns. 
- Here comes the importance of shape.
- As we can concatenate arrays in both directions i.e., rows or columns, the shape must be compatible in the direction in which we want to concatenate. 

Example 1:
- Lets try to place the second array, bellow the first array. That may be called *row wise concatenation or axis 0 concatenation*. 
- In order to perform such concatenation i.e., placing the second array bellow the first array, the number of columns must be equal in both of these arrays. This condition is surely met here. 
- - This can be seen as adding more rows to an already existing array.

In [7]:
z = np.concatenate((x,y), axis = 0)
z

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [-1, -2, -3, -4],
       [-5, -6, -7, -8]])

Example 2:
- Now lets try to place the second array, at the right side of the first array. That may be called *column wise concatenation or axis 1 concatenation*. 
- In order to perform such concatenation i.e., placing the second array at the right side of the first array, the number of rows must be equal in both of these arrays. This condition is surely met here. 
- This can be seen as adding more columns to an already existing array.

In [8]:
z = np.concatenate((x,y), axis = 1)
z

array([[ 1,  2,  3,  4, -1, -2, -3, -4],
       [ 5,  6,  7,  8, -5, -6, -7, -8]])

## Array Stacking


### Stacking Single Dimensional Arrays
- **Syntax**:
  - `np.stack(tuple_of_arrays)`

In [9]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

shape1 = x.shape
shape2 = y.shape

print(f"The shape of first array is : {shape1}\nThe Shape of the second array is : {shape2}")

The shape of first array is : (5,)
The Shape of the second array is : (5,)


In [10]:
z = np.stack((x , y))
print(z.shape)
print(z)

(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**Discussion**
- We can see that the shape of the new array, created by the stacking, is not the same as the original arrays. Rather, the combined array have created a new dimension and now we have a 2D array instead of a 1D array. 
- So, as we know, that the stacking creates new dimensions, we can choose the direction where the new dimension should be created. That means we can stack these arrays horizontally or vertically. Same as array concatenation, this is achieved using the `axis` arguments. 

**Example 1**:
- Lets combine the arrays in such a way that the new array is placed at the bottom of the first array and the new array is now a 2D array. This will be achieved using the first `axis`. 

In [11]:
z = np.stack((x,y), axis = 0)
print(z)
print(z.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


**Example 2**:
- Lets combine the arrays in such a way that the new array is placed at the right side of the first array and the new array is now a 2D array. This will be achieved using the second `axis`. 
- Unlike the array concatenation, stacking arrays side by side will not result in a simple array that have all the elements of both of these arrays, rather, the first single dimensional array will be arranged in the shape of a column and the second single dimensional array will also be arranged in the same way adn them both of these are combined into a new 2D array.

In [12]:
z = np.stack((x,y), axis = 1)
print(z)
print(z.shape)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
(5, 2)


**Example 3**:
- Combining more than two arrays using stacking.

In [13]:
# combining in the column fashion

another_array = np.array([11,12,13,14,15])
z = np.stack((x,y,another_array), axis = 1)
print(z)
print(z.shape)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
(5, 3)


In [14]:
# combining in the row fashion

z = np.stack((x,y,another_array), axis = 0)
print(z)
print(z.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


### Stacking 2D/Multi-Dimensional Arrays 

In [15]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
y = np.array([
    [-1,-2,-3,-4],
    [-5,-6,-7,-8]
])

shape1 = x.shape
shape2 = y.shape

print(f"The shape of first array is : {shape1}\nThe Shape of the second array is : {shape2}")

The shape of first array is : (2, 4)
The Shape of the second array is : (2, 4)


#### Stacking Vertically / Adding More Rows
- This is done using `vstack()` function. 

In [18]:
vertically_stacked = np.vstack((x,y))
print(vertically_stacked.shape)
print(vertically_stacked)

(4, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [-1 -2 -3 -4]
 [-5 -6 -7 -8]]


#### Stacking Horizontally / Adding More Columns
- This is done using `hstack()` function. 

In [19]:
horizontally_stacked = np.hstack((x, y))
print(horizontally_stacked.shape)
print(horizontally_stacked)

(2, 8)
[[ 1  2  3  4 -1 -2 -3 -4]
 [ 5  6  7  8 -5 -6 -7 -8]]


**Discussion**
- The `hstack` and `vstack` functions give us the same consolidated arrays as `concatenate` function using `axis = 1` and `axis = 0` respectively. 

### Combining Single Dimensional Arrays with Multi-Dimensional Arrays
- So far we have seen that in order to combine two arrays, there shape should be compatible along the desired axis but there are scenarios in which we may need to combine arrays with different shapes. 


#### Adding Single Row to a 2D Array

In [37]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

y = np.array([9,10,11,12])

print(x.shape)
print(y.shape)

(2, 4)
(4,)


In [ ]:
"""
=================
Both of the following methods will be unable to combine these rows 
and will raise the following value error
ValueError: all input arrays must have the same shape
=================

z = np.concatenate((x, y))
z = np.stack((x,y))

"""

- Lets reshape the single dimensional array as a 2D array having the elements as a single row and multiple columns. 

In [38]:
print(f"Old shape of y : {y.shape}")
y = y.reshape(1,4)
print(f"New sahpe of y : {y.shape}")
print(f"And the new array looks like this : \n{y}")


Old shape of y : (4,)
New sahpe of y : (1, 4)
And the new array looks like this : 
[[ 9 10 11 12]]


- Lets now try to combine these arrays. 

In [49]:
print(f"The shape of these two arrays is {x.shape}, {y.shape}")

# adding row using concatenate
combined = np.concatenate((x,y), axis = 0)
print(combined, end = '\n\n')

# resetting combined array
combined.fill(0)

combined = np.vstack((x,y))
print(combined, end= '\n\n')



The shape of these two arrays is (2, 4), (1, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



#### Adding a Single Column to a 2D Array

In [59]:
x = np.zeros((4,4))

y = np.array([9,10,11,12])

print(x.shape)
print(y.shape)

(4, 4)
(4,)


- Lets reshape our single dimensional array to a column. This will be a 2D array having 4 rows and a single column. 

In [60]:
print(f"Old shape of y : {y.shape}")
y = y.reshape(4,1)
print(f"New sahpe of y : {y.shape}")
print(f"And the new array looks like this : \n{y}")

Old shape of y : (4,)
New sahpe of y : (4, 1)
And the new array looks like this : 
[[ 9]
 [10]
 [11]
 [12]]


- Now Add this column to our 2D array

In [61]:
print(f"The shape of these two arrays is \n{x.shape} \n{y.shape}")

# adding row using concatenate
combined = np.concatenate((x,y), axis = 1)
print(combined, end = '\n\n')

# resetting combined array
combined.fill(0)

combined = np.hstack((x,y))
print(combined, end= '\n\n')


The shape of these two arrays is 
(4, 4) 
(4, 1)
[[ 0.  0.  0.  0.  9.]
 [ 0.  0.  0.  0. 10.]
 [ 0.  0.  0.  0. 11.]
 [ 0.  0.  0.  0. 12.]]

[[ 0.  0.  0.  0.  9.]
 [ 0.  0.  0.  0. 10.]
 [ 0.  0.  0.  0. 11.]
 [ 0.  0.  0.  0. 12.]]



## Adding The 3rd Dimension / Depth Wise Combining

In [64]:
x = np.ones(5)
y = np.zeros(5)
print(x,y)
print(x.shape, y.shape)

[1. 1. 1. 1. 1.] [0. 0. 0. 0. 0.]
(5,) (5,)


In [65]:
z = np.stack((x,y))
print(z.shape)
print(z)

(2, 5)
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


**Discussion:**
- Note here that the newly combined array is not a single dimensional array having all the elements of first and second array combined, rather, the newly created is a 2D array that has 2 rows and 5 columns. This array combining method has created a new dimension instead of simply combining.


**Lets Now Add a Third Dimension**

In [68]:
print(f"The old shape of z is {z.shape}")
new_arr = np.random.randint(1,11,(2,5))
print(f"The shape of newly created array is : {new_arr.shape}\n\n")

combined = np.stack((z,new_arr))
print(f"The shape of combined array is : {combined.shape}")
print(combined)

The old shape of z is (2, 5)
The shape of newly created array is : (2, 5)


The shape of combined array is : (2, 2, 5)
[[[1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0.]]

 [[8. 1. 4. 2. 6.]
  [8. 7. 3. 4. 3.]]]


# Deleting Data from Numpy Arrays


In [71]:
an_array = np.random.randint(1,11,(5,5))
an_array

array([[ 7,  1,  9, 10,  8],
       [ 4,  6,  2, 10, 10],
       [ 1,  3,  2,  3,  6],
       [ 2,  4,  5,  5,  5],
       [ 2,  7,  5,  8,  8]])

## Deleting Specic Rows