<h1 align = center>Numpy Library - Indexing, Slicing and Filtering Arrays</h1>

## Indexing Array Elements

### Indexing 1D Arrays

In [1]:
import numpy as np

In [2]:
an_array = np.array([1,2,3,4,5])
second_element = an_array[1]
fifth_element = an_array[4]
first_element_from_last = an_array[-1]
third_element_from_last = an_array[-3]


print(f'second element : {second_element}')
print(f'fifth element : {fifth_element}')
print(f'first element from the last : {first_element_from_last}')
print(f'third element from the last : {third_element_from_last}')

second element : 2
fifth element : 5
first element from the last : 5
third element from the last : 3


### Indexing ND-Arrays

In [8]:
# defining a 2D array
b_array = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

#### Accessing rows

In [12]:
print(f'first row : {   b_array[0]  }')
print(f'second row : {  b_array[1]  }')
print("____________")
print(f'accessing all rows : \n{b_array[:]}')

first row : [1 2 3 4 5]
second row : [ 6  7  8  9 10]
____________
accessing all rows : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


#### Accessing Columns 

In [ ]:
print(f'second column : {    b_array[:,2]   }')